### PR TITLE
fix opencc serialization error

### PR DESCRIPTION
**Pull request by chenhesen**
fix bug for issue https://github.com/alibaba/data-juicer/issues/81

### CODE REVIEW

**Review by HYLcool — DISMISSED** [review]
LGTM if related tests are all passed.

The modification in this PR conflicts with PR #82 , and I will fix it in that PR.

**Comment by simplew2011** [comment]
image

好像没起效

**Review by HYLcool — COMMENTED** [review]
BTW, the global varaibles `fingerprint_warnings` seems not "global". Please check if there is something wrong in this part.

**Comment by chenhesen** [comment]
> image
> 
> 好像没起效

你好，更新完代码后，我们没有复现出该错误。
我使用的环境：
datasets==2.11.0
dill==0.3.4
opencc==1.1.6
可以检查下对应库的版本，然后删掉cache文件后再试试

**Comment by simplew2011** [comment]
datasets==2.11.0
dill==0.3.4
这两个版本引起的，已通过

**Review by HYLcool — APPROVED** [review]
Nice~

**Pull request merged**
