### PR TITLE
fix readme link

### PR DESCRIPTION
**Pull request by zhijianma**

### CODE REVIEW

**Comment by drcege** [comment]
@yxdyc  

 Besides, the subsection titled `Documentation Index | 文档索引` is always presented side by side in both [README.md](https://github.com/alibaba/data-juicer/blob/main/README.md#documentation-index--%E6%96%87%E6%A1%A3%E7%B4%A2%E5%BC%95-) and [README_ZH.md](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md#documentation-index--%E6%96%87%E6%A1%A3%E7%B4%A2%E5%BC%95-). Could this be considered slightly redundant? Especially for developers who are not familiar with Chinese, it might come across as a mess.

**Review by yxdyc — APPROVED** [review]
LGTM

**Comment by HYLcool** [comment]
Please change the version to 0.2.0 in the data_juicer/__init__.py also~

**Comment by yxdyc** [comment]
> @yxdyc
> 
> Besides, the subsection titled `Documentation Index | 文档索引` is always presented side by side in both [README.md](https://github.com/alibaba/data-juicer/blob/main/README.md#documentation-index--%E6%96%87%E6%A1%A3%E7%B4%A2%E5%BC%95-) and [README_ZH.md](https://github.com/alibaba/data-juicer/blob/main/README_ZH.md#documentation-index--%E6%96%87%E6%A1%A3%E7%B4%A2%E5%BC%95-). Could this be considered slightly redundant? Especially for developers who are not familiar with Chinese, it might come across as a mess.

Agree, please @zhijianma also modify accordingly.

**Review by yxdyc — APPROVED** [review]

**Pull request merged**
