### PR TITLE
Docs/bad data exhibition

### PR DESCRIPTION
**Pull request by HYLcool**
As the title says.

### CODE REVIEW

**Comment by HYLcool** [comment]
MMC4 dataset is in analysis for these 2 docs.

**Review by yxdyc — APPROVED** [review]
The todo item can be finished in next PR: 
[add "bad" data examples from the analysis result of MMC4 dataset for these 2 docs. ]

**Comment by HYLcool** [comment]
- "Bad" data examples from MMC4 have been added to the exhibition
- Fix bugs for mmc4_to_dj/dj_to_mmc4 tools: there might be multiple images matching the same sentence, so we need to support adding multiple image_special_tokens to the same sentence in mmc4_to_dj and parsing them correctly in dj_to_mmc4.

**Review by yxdyc — APPROVED** [review]
The modifications lgtm.

**Pull request merged**
